FROM ubuntu:18.04            #FROM creates a layer from the ubuntu:18.04 Docker image.
COPY . /app                  #COPY adds files from your Docker client’s current directory.
RUN make /app                #RUN builds your application with make.
CMD python /app/app.py       #CMD specifies what command to run within the container.